- name: Install apache2
  apt: pkg=apache2 state=installed

- name: Disable default Apache site
  command: a2dissite default removes=/etc/apache2/sites-enabled/default
  notify: restart apache

- name: Enable Apache SSL module
  command: a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.load

